//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAssignmentRoster
    {
        public int CourseAssignmentRosterID { get; set; }
        public int CourseAssignmentID { get; set; }
        public int CourseRosterID { get; set; }
        public Nullable<short> PointsEarned { get; set; }
        public Nullable<decimal> GradePercent { get; set; }
    
        public virtual CourseAssignment CourseAssignment { get; set; }
        public virtual CourseRoster CourseRoster { get; set; }
    }
}
