//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseRosters = new HashSet<CourseRoster>();
            this.CourseAssignments = new HashSet<CourseAssignment>();
        }
    
        public int CourseID { get; set; }
        public short SubjectAreaID { get; set; }
        public byte GradeLevelID { get; set; }
        public int TeacherID { get; set; }
        public string CourseName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsArchived { get; set; }
        public string CourseDescription { get; set; }
    
        public virtual ICollection<CourseRoster> CourseRosters { get; set; }
        public virtual ICollection<CourseAssignment> CourseAssignments { get; set; }
        public virtual GradeLevel GradeLevel { get; set; }
        public virtual SubjectArea SubjectArea { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
