//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedRole
    {
        public RequestedRole()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public byte RequestedRoleID { get; set; }
        public string RequestedRoleName { get; set; }
    
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
