//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Courses = new HashSet<Course>();
            this.CourseRosters = new HashSet<CourseRoster>();
            this.UserInfo1 = new HashSet<UserInfo>();
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int UserInfoID { get; set; }
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<byte> GradeLevel { get; set; }
        public byte RequestedRoleID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<CourseRoster> CourseRosters { get; set; }
        public virtual RequestedRole RequestedRole { get; set; }
        public virtual ICollection<UserInfo> UserInfo1 { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
